# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 08:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170925_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 25, 8, 22, 3, 767652, tzinfo=utc)),
        ),
    ]
